[package]
name = "sand_app"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.19.2"
gtk = { version = "0.8.1", package = "gtk4", features = ["v4_12"] }
